services:
  kuroai:
    image: ghcr.io/gomatigit/kuroai:latest
    container_name: kuroai
    restart: unless-stopped
    pull_policy: always
    working_dir: /app

    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      KURO_OWNER_USER_ID: ${KURO_OWNER_USER_ID}
      ELEVENLABS_API_KEY: ${ELEVENLABS_API_KEY}
      KURO_VOICE_ID: ${KURO_VOICE_ID}
      KURO_DATA_DIR: /app/data

    volumes:
      - ./data:/app/data